### ISSUE TITLE
bug: sort logic is incorrect

### ISSUE THREAD

**Issue by samccone** [mojotech/helios#10]
https://github.com/mojotech/helios/blob/master/js/components/forecast_hours.js#L15-L16

> If compareFunction is not supplied, elements are sorted by converting them to strings and comparing strings in Unicode code point order

```
var scores = [1, 10, 2, 21]; 
scores.sort(); // [1, 10, 2, 21]
```

:goat:

**Comment by cpjolicoeur** [comment]
Also, why not just (once you sort correctly) `sort().reverse()[0]` instead of slicing and dicing?
