### ISSUE TITLE
bug: what happens when it is really cold outside?

### ISSUE THREAD

**Issue by samccone** [mojotech/helios#11]
https://github.com/mojotech/helios/blob/master/js/components/forecast_hours.js#L17

I think this line might fail

----

and this line

https://github.com/mojotech/helios/blob/master/js/components/forecast_hours.js#L29

**Comment by joelhawksley** [comment]
How about padding the temp values +100?

**Comment by samccone** [comment]
I think this would mask the issue, not "fix" it :)

**Comment by joelhawksley** [comment]
we could always do the calculation in Kelvin...

but in all seriousness, how would you propose fixing this?

**Comment by samccone** [comment]
I would start by asking these questions to arrive at a solution:

What is the goal of the line of code in english?
Why will it fail when it is cold?

**Comment by joelhawksley** [comment]
The goal of the logic in on line 17 is to calculate the difference between the highest and lowest temperatures in a day. It could potentially fail when one or both values are negative.

**Comment by joelhawksley** [comment]
Closing due to deprecation of this feature.
