### ISSUE TITLE
Slack integration fails if current time is not yet set by the system

### ISSUE THREAD

**Issue by mfrost** [mojotech/helios#121]
`error.log` contains messages like this:

```
t=1969-12-31T17:00:09-0700 lvl=warn msg="Failed to start service: Error: Post https://slack.com/api/rtm.start: dial tcp: lookup slack.com on 192.168.1.1:53: dial udp 192.168.1.1:53: connect: network is unreachable" service=slack
```

@begizi says SSL validation fails because we're not actually in 1969...

For now, this can be fixed by bumping the helios service via `sudo systemctl restart helios.service`.

**Comment by cpjolicoeur** [comment]
wait, this isn't 1969?

![](https://media.giphy.com/media/mNdOc0Aziv88E/giphy.gif)

**Comment by planetmcd** [comment]
Hey, that was great year.

**Comment by cpjolicoeur** [comment]
Great summer at least.  Well, that's what I've heard...

**Comment by begizi** [comment]
Will be updating slack service to be more tolerant of these types of issues and retry at a given interval.

**Comment by begizi** [comment]
#148 should fix. Running manual test on pi then closing
