### ISSUE TITLE
Add pokemon go service

### ISSUE THREAD

**Issue by begizi** [mojotech/helios#141]
Inspiration: https://github.com/jacobmarshall/pokevision-cli
Icons: https://ugc.pokevision.com/images/pokemon/<pokemon_id>.png

Include distance underneath the icon as well as a progress bar style countdown to expiration.
![](http://d.pr/i/1eLPI+)

**Comment by THEKaminsky** [comment]
Okay. So this is a really fun idea, but what if there are 12 of them out there. High volume of pokemon could be no good depending how you want to display it.

**Comment by mordecai174** [comment]
wat.

**Comment by begizi** [comment]
We can add a filter array to the config.json file to hide common pokemon for this area

**Comment by begizi** [comment]
External apis closed down 😭 Closing this issue since it really wouldn't be worth battling an unofficial api forever and ever. https://twitter.com/PokeVisionGo/status/759666743115513856
