### ISSUE TITLE
Add commute time estimate

### ISSUE THREAD

**Issue by mordecai174** [mojotech/helios#28]
Close to the end of the day it might be nice to have an estimated commute time for heading to the east bay or anywhere outside of providence.

**Comment by mordecai174** [comment]
![image](https://cloud.githubusercontent.com/assets/4331569/9022425/ff961a84-3842-11e5-8794-65079dab3982.jpg)

**Comment by samccone** [comment]
oh that is a greaaaaaat idea

@fcanas do you know what apple uses for this?

**Comment by samccone** [comment]
https://developers.google.com/maps/documentation/javascript/?csw=1#GDirections.getDuration

**Comment by fcanas** [comment]
Yeah. I've built this before. http://mobile.mapquest.com/commute/

We need a direction service that accounts for traffic. I'm unaware of any free ones.

**Comment by mordecai174** [comment]
@fcanas are they expensive?

**Comment by fcanas** [comment]
Depends. If we want to hack it together like we did RandomRun, probably not. If we want access to congestion data, it's tens of thousands of dollars or more.

**Comment by samccone** [comment]
:money_with_wings: :goat:

**Comment by fcanas** [comment]
:fire: :moneybag:

**Comment by mordecai174** [comment]
ok... probably not worth it to project onto the wall.

**Comment by fcanas** [comment]
We could do it with google maps

> For driving directions: Google Maps API for Work customers can specify the departure_time to receive trip duration considering current traffic conditions. The departure_time must be set to within a few minutes of the current time.

[Google Maps API for Work](https://www.google.com/work/mapsearth/products/mapsapi.html) << "Contact Sales"

**Comment by fcanas** [comment]
To clarify: 

You need to contact sales (and then pay some yet unknown amount of money) to get an account that allows you to make route requests that have transit time that accounts for traffic conditions.

**Comment by joelhawksley** [comment]
I've reached out to Google about getting access to traffic conditions.

**Comment by joelhawksley** [comment]
Just heard back. It's $10k/yr for the most basic option that includes this data. :moneybag: :fire:

**Comment by mordecai174** [comment]
wellp, hahah, i'll just continue to check my phone. sorry helios

**Comment by fcanas** [comment]
Called it.

**Comment by joelhawksley** [comment]
To be fair, they were nice enough to call me and share the news.

**Comment by fcanas** [comment]
That's how ≥$10k contracts work. You get to talk to people and get treated like a person. :performing_arts:

**Comment by samccone** [comment]
🎒👟🌂
