### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by mordecai174** [mojotech/helios#33]
<p align="center">:space_invader: Implement this design, <b>1-to-1</b>. :space_invader: </p>

![helios](https://cloud.githubusercontent.com/assets/4331569/9039871/5cb500c4-39cc-11e5-8370-7a5727cb2a3f.png)

-----

### Tasks

* [ ] #31 -- Remove Bootstrap
* [ ] #24 -- 2 day look ahead
* [ ] #34 -- clock components
* [x] #35 -- per channel chat notifications
* [ ] #36 -- github feed

**Comment by samccone** [comment]
:+1:

**Comment by joelhawksley** [comment]
Updated to include Remove Bootstrap task
