### ISSUE TITLE
Implement clock component

### ISSUE THREAD

**Issue by samccone** [mojotech/helios#34]
clocks should be able to take an offset param for the time.

<img width="135" alt="screen shot 2015-08-03 at 10 44 49 am" src="https://cloud.githubusercontent.com/assets/883126/9039932/baf1732a-39cc-11e5-8246-a243fd459963.png">

**Comment by mordecai174** [comment]
FWIW, it might be nice to do this with svg. http://codepen.io/TheRealAlan/pen/zCdbH lot's of good examples

**Comment by mordecai174** [comment]
https://www.dropbox.com/s/xxwtow9q7b0ngr7/clock.svg?dl=0
