### ISSUE TITLE
Add secondary clocks for BLDR and NYC

### ISSUE THREAD

**Issue by joelhawksley** [mojotech/helios#74]

**Comment by jnb101** [comment]
BOU = BLDR (for consistency; only relevant if clocks are labelled like that)

**Comment by joelhawksley** [comment]
@jnb101 why did you close this issue?

**Comment by jnb101** [comment]
A: because I'm bad at Github. Sorry... Was thinking in my head "close window and submit comment" not "close issue"

**Comment by joelhawksley** [comment]
@jnb101 no problem! I've fixed the title.
