### ISSUE TITLE
auto-off might be broken

### ISSUE THREAD

**Issue by jnb101** [mojotech/helios#96]
The display did not turn off last night (night of 9/9-9/10); it did the night before.

**Comment by joelhawksley** [comment]
@jnb101 did it turn off last night? (9/10-9/11)

**Comment by jnb101** [comment]
no :(

**Comment by joelhawksley** [comment]
@jnb101 I think we fixed this. Let's keep a look out.

**Comment by jnb101** [comment]
I'll peak in on dropcam over the weekend

- -
sent from my phone. please forgive typos and brevity.

**Comment by joelhawksley** [comment]
Per @jnb101, this has been resolved.
